/*

 STANDARDBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\harry\Documents\CodingProjects\gameboy\octopode-ocean\sprites\BackgroundSprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define StandardBackgroundWidth 32
#define StandardBackgroundHeight 32
#define StandardBackgroundBank 0

extern unsigned char StandardBackground[];

/* End of STANDARDBACKGROUND.H */
