/*

 STANDARDBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : Z:\home\harry\Documents\CodingProjects\gameboy\octopode-ocean\sprites\BackgroundSprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define StandardBackgroundWidth 40
#define StandardBackgroundHeight 36
#define StandardBackgroundBank 0

extern unsigned char StandardBackground[];

/* End of STANDARDBACKGROUND.H */
