#pragma once
#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 144

#define DESPAWN_X 255
#define DESPAWN_Y 255

#define DEBUG 0

// const int OCTOPUS_SPRITE_NUMBER = 0;

#define OCTOPUS_SPRITE_NUMBER 0
#define MOVEMENT_SPEED 1
#define DEFAULT_DELAY 16
#define MOVEMENT_DELAY 16
#define SHOT_SPEED_MULTIPLIER 2
#define SCROLL_SPEED 1
#define INK_RADIUS 8
#define INK_SHOT_AMOUNT 4
#define DIVER_AMOUNT 4
#define DIVER_ACTIVATION_RANGE 80
#define DIVER_RADIUS 16
#define DIVER_SCREEN_WIDTH 248
#define DIVER_SCREEN_HEIGHT 248
#define DIVER_ROAM_SPEED 1
#define DIVER_CHASE_SPEED 4
#define DIVER_STARTING_HEALTH 2

#define DIVER_SPAWN_INTERVAL 60

const enum directions{NORTH, SOUTH, WEST, EAST, NORTH_WEST, NORTH_EAST, SOUTH_WEST, SOUTH_EAST};