/*

 TINYOCTOPUS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TinyOctopus[] =
{
  0x00,0x18,0x18,0x24,0x3C,0x66,0x3C,0x42,
  0x3C,0x4A,0x14,0x6A,0x55,0xAA,0x28,0x57,
  0x00,0x18,0x18,0x24,0x3C,0x66,0x3C,0x42,
  0x3C,0x5A,0x14,0x6A,0x55,0xAA,0x28,0x57
};

/* End of TINYOCTOPUS.C */
